name: Build and Release Electron App

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libfontconfig-dev fakeroot xvfb icnsutils graphicsmagick xz-utils libsecret-1-dev libgtk-3-dev libnss3 libxss1 libasound2t64

    - name: Install dependencies
      run: npm install

    # Lo script "package" esegue già "vite build", quindi non è necessario un passaggio separato.
    - name: Package Electron app
      run: npm run package -- --publish never
      # IMPORTANTE: La chiave API NON viene inclusa qui per motivi di sicurezza.
      # L'app è progettata per leggerla dall'ambiente dell'utente al momento dell'esecuzione.

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: installer-${{ matrix.os }}
        path: |
          release/*
          !release/builder-debug.yml

  release:
    name: Attach Assets to GitHub Release
    needs: build # Questo job parte solo se tutti i "build" hanno successo
    runs-on: ubuntu-latest

    steps:
    - name: Download all installer artifacts
      uses: actions/download-artifact@v4
      with:
        path: installers
        # L'azione creerà sottocartelle per ogni artefatto, es. installers/installer-windows-latest/

    - name: Upload assets to release
      uses: softprops/action-gh-release@v2
      with:
        # Questo pattern cerca tutti i file di installazione nelle sottocartelle
        files: installers/*/*
      env:
        # Il token è fornito automaticamente da GitHub Actions
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}